### ISSUE TITLE
connection.stop very slow on Ruby 2.2.3

### ISSUE THREAD

**Issue by MrJaba** [ruby-amqp/bunny#349] opened 2015-09-15 13:13 UTC
Hi, 

I'm not sure what could be causing this, but thought I'd report just in case it's something obvious. 

I recently switched to Ruby 2.2.3 and since then disconnecting from Bunny in client code has been throwing timeouts. 

Simple test:

```
rbenv local 2.1.6
bundle exec rails console
conn = Bunny.new.start
Benchmark.realtime { conn.stop } #=> 0.0036s
```

```
rbenv local 2.2.3
bundle exec rails console
conn = Bunny.new.start
Benchmark.realtime { conn.stop } #=> 30.004
```

I think the method in question is this one:
https://github.com/ruby-amqp/bunny/blob/2738b07b3df40580d74b23f248061438d6771cba/lib/bunny/session.rb#L348

But nothing looks particularly suspicious about it. 

Let me know if I can provide more information or if this is something completely obvious. 

Thanks

**Comment by michaelklishin** [comment] 2015-09-15 13:27
It's not something obvious. The method need profiling.

**Comment by bdusauso** [comment] 2015-12-04 15:49
After shallow investigation it seems it has nothing to do with Ruby version.
The problem is clearly located at https://github.com/ruby-amqp/bunny/blob/2738b07b3df40580d74b23f248061438d6771cba/lib/bunny/session.rb#L877 

Unfortunately I don't have enough spare time at this moment to investigate further.

Hope this helps.

**Comment by michaelklishin** [comment] 2015-12-04 15:52
@bdusauso how exactly did you come to this conclusion? Joining a thread will wait so for sampling profilers it will seem like 99% of time is spent there while all that method does it waiting on something else to finish (and in case of I/O loop in Bunny, that can have valid reasons to run for a while).

**Comment by bdusauso** [comment] 2015-12-04 16:09
Well, to be honest I've puts some logging statement in the code and it "hangs" for 30 seconds between 
`@reader_loop.terminate_with(ShutdownSignal)` and `@reader_loop.join`

```ruby
    def maybe_shutdown_reader_loop
      if @reader_loop
        @reader_loop.stop
        if threaded?
          # this is the easiest way to wait until the loop
          # is guaranteed to have terminated
          @reader_loop.terminate_with(ShutdownSignal)
          # joining the thread here may take forever
          # on JRuby because sun.nio.ch.KQueueArrayWrapper#kevent0 is
          # a native method that cannot be (easily) interrupted.
          # So we use this ugly hack or else our test suite takes forever
          # to run on JRuby (a new connection is opened/closed per example). MK.
          if defined?(JRUBY_VERSION)
            sleep 0.075
          else
            @reader_loop.join
          end
        else
          # single threaded mode, nothing to do. MK.
        end
      end
```

It doesn't always do that though, but it is quite often.
Moreover when using only one thread it works perfectly fine.

That's how I came to this conclusion.

Hope this helps.

**Comment by michaelklishin** [comment] 2015-12-04 16:11
@bdusauso that means the I/O thread takes time to terminate, not much else.

**Comment by michaelklishin** [comment] 2015-12-10 22:46
Closing as there are no details for us to improve anything.

**Closed** 2015-12-10 22:45 UTC
